/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:59e42a9c-959c-4672-90ed-8310fd3bff33",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_TQ0nGNZIl",
    "aws_user_pools_web_client_id": "59qc79qgkqhht8nv7jdm5prfk9",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_content_delivery_bucket": "amplifyapp-20210815112140-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d2b06bf5ewuib7.cloudfront.net",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "blogs-dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
